# Run this command to start the services:
# docker compose up
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3001"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    command: >
      sh -c "npm run start"